### ISSUE TITLE
Let's refactor this project with new tech!

### ISSUE THREAD

**Issue by keainye** [Zxilly/CamShow#1]
How about refactoring this project with React/Vue + Golang?

**Comment by Zxilly** [comment]
We can make an user-friendly panel.
I feel good about the frontend.

**Comment by keainye** [comment]
Are there any instance of the project？

**Comment by Zxilly** [comment]
https://photo.learningman.top

**Comment by keainye** [comment]
How about add a function of catagory to photos?
